[alias]
b = "run --quiet --manifest-path tools/release-builder/Cargo.toml --target-dir target/cargo-b-tool --"
check-linux = "check --workspace --all-targets --locked --target x86_64-unknown-linux-gnu"
build-linux = "build --workspace --release --locked --target x86_64-unknown-linux-gnu"
test-linux = "test --workspace --locked --target x86_64-unknown-linux-gnu"
