use std::net::{IpAddr, SocketAddr};

use serde::{Deserialize, Serialize};

use super::{
    Config, loopback_bind,
    origins::{normalize_http_origin, url_origin},
};
use crate::{databases::protocol::Protocol, utils::constants::ports};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct TlsConfig {
    pub cert: String,
    pub key: String,
}

impl TlsConfig {
    pub fn configured(&self) -> bool {
        !self.cert.trim().is_empty() || !self.key.trim().is_empty()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ListenerConfig {
    pub enabled: bool,
    pub bind: String,
    pub tls: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ClickhouseConfig {
    pub enabled: bool,
    pub bind: String,
    pub http_bind: String,
    pub tls: bool,
}

impl ClickhouseConfig {
    pub fn enabled(bind: String, http_bind: String) -> Self {
        Self {
            enabled: true,
            bind,
            http_bind,
            tls: false,
        }
    }

    pub fn disabled(bind: String, http_bind: String) -> Self {
        Self {
            enabled: false,
            bind,
            http_bind,
            tls: false,
        }
    }
}

impl Default for ClickhouseConfig {
    fn default() -> Self {
        Self::disabled(
            loopback_bind(ports::CLICKHOUSE),
            loopback_bind(ports::CLICKHOUSE_HTTP),
        )
    }
}

impl ListenerConfig {
    pub fn enabled(bind: String) -> Self {
        Self {
            enabled: true,
            bind,
            tls: false,
        }
    }

    pub fn disabled(bind: String) -> Self {
        Self {
            enabled: false,
            bind,
            tls: false,
        }
    }
}

impl Default for ListenerConfig {
    fn default() -> Self {
        Self::disabled("127.0.0.1:0".to_string())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ApiConfig {
    pub host: String,
    pub port: u16,
    /// Retained only to load v0.6 configuration files. Host headers are not
    /// an authorization boundary and this value has no runtime effect.
    #[serde(skip_serializing)]
    pub trusted_hosts: Vec<String>,
    /// Accepted only so configurations generated by older panels keep loading.
    /// The panel owns the daemon's public address; this value never affects
    /// listener binding, request validation, or URL generation.
    #[serde(skip_serializing)]
    pub fqdn: String,
    pub trusted_origins: Vec<String>,
    pub ssl: ApiSslConfig,
}

impl Default for ApiConfig {
    fn default() -> Self {
        Self {
            host: "127.0.0.1".to_string(),
            port: ports::API,
            trusted_hosts: Vec::new(),
            fqdn: String::new(),
            trusted_origins: Vec::new(),
            ssl: ApiSslConfig::default(),
        }
    }
}

impl Config {
    pub fn protocol_enabled(&self, protocol: Protocol) -> bool {
        protocol.engine().listener(self).enabled
    }

    pub fn cors_allowed_origins(&self) -> Vec<String> {
        let mut origins = Vec::new();
        if let Some(origin) = url_origin(&self.remote) {
            push_unique(&mut origins, origin);
        }
        for origin in &self.api.trusted_origins {
            if let Some(origin) = normalize_http_origin(origin) {
                push_unique(&mut origins, origin);
            }
        }
        origins
    }

    pub fn websocket_jwt_secret(&self) -> &[u8] {
        self.jwt_signing_key.as_bytes()
    }
}

impl ApiConfig {
    pub fn bind_addr(&self) -> String {
        let host = self.host.trim();
        host.parse::<IpAddr>().map_or_else(
            |_| format!("{host}:{}", self.port),
            |address| SocketAddr::new(address, self.port).to_string(),
        )
    }
}

fn push_unique(values: &mut Vec<String>, value: String) {
    if !values.contains(&value) {
        values.push(value);
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ApiSslConfig {
    pub enabled: bool,
    pub cert: String,
    pub key: String,
    pub require_client_cert: bool,
    pub client_ca: String,
}
